# This workflow will sign an installer for the FLEx Variant Generator utility.

name: VarGen Sign and Release

on:
  push:

jobs:
  preparation:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: VariantGenerator
          path: InstallerVarGen/Output/VariantGeneratorDllSetup.exe
          if-no-files-found: error

  sign-installer:
    name: Sign VarGen installer
    needs: preparation
    uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    with:
      artifact: VariantGenerator
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  create-release:
    name: Create Release
    needs: sign-installer
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: VariantGenerator

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: VariantGeneratorDllSetup.exe
          body: |
            Release for version ${{ github.ref }}
          draft: true
